#!/usr/bin/python
# -*- coding: utf-8 -*-

import os

DB_USER = "root"
DB_PASSWORD = "123456"
DB_NAME = "dbrobot"

UNIXSOCKET_DEBIAN = "/var/run/mysqld/mysqld.sock"
UNIXSOCKET_REDCENT = "/var/lib/mysql/mysql.sock"

DB_SERVER = "localhost"

TB_ACCOUNT = "tb_account"
TB_MISC = "tb_misc"
TB_LOG = "tb_log"
TB_QUOTA = "tb_quota"
TB_APIRECORD = "tb_apirecord"
TB_REMOTELOG = "tb_remotelog"
TB_PRODUCT = "tb_product"
TB_APITRACE = "tb_apitrace"
TB_SERVERTASK = "tb_stask"
TB_SESSION = "tb_session"
TB_DATACENTER = "tb_datacenter"
TB_HOSTPOOL = "tb_hostpool"
TB_OFFERING = "tb_offering"
TB_USER = "tb_user"
TB_CLIENTPOLICY = "tb_clientpolicy"
TB_RELUSERGROUP = "tb_relusergroup"
TB_USERGROUP = "tb_usergroup"
TB_USERVM = "tb_reluservm"
TB_TERMINALUSERVM = "tb_terminaluservm"
TB_VM = "tb_vm"
TB_HOST = "tb_host"
TB_RELUSERCLIENT = "tb_reluserclient"
TB_DESKCLIENT = "tb_deskclient"
TB_SERVERHOST = "tb_shost"
TB_SERVERPRIMARYSTORAGE = "tb_sprimarystorage"
TB_PRIMARYSTORAGE = "tb_primarystorage"
TB_RELPRIMARYSTORAGEPOOL = "tb_relprimarystoragepool"
TB_ROUTE = "tb_route"
TB_INTERFACE = "tb_interface"
TB_IMAGECACHE = "tb_imagecache"
TB_IMAGE= "tb_image"
TB_RELIMAGEBACKUPSTORAGE = "tb_relimagebackupstorage"

TB_BACKUPSTORAGE = "tb_backupstorage"
TB_RELBACKUPSTORAGEDATACENTER = "tb_relbackupstoragedatacenter"

TB_L2NETWORK = "tb_l2network"
TB_L2VLANNETWORK = "tb_l2vlannetwork"
TB_L3NETWORK = "tb_l3network"
TB_IPPOOL = "tb_ippool"
TB_USEDIP = "tb_usedip"
V_USEDIP = "v_usedip"
TB_VIP = "tb_vip"
TB_EIP = "tb_eip"
TB_VIRTUALROUTEROFFERING = "tb_virtualrouteroffering"
TB_SERVERVM = "tb_svm"
TB_PORTFORWARDINGRULE = "tb_portforwardingrule"
TB_SECURITYZONE = "tb_securityzone"
V_SECURITYZONE = "v_securityzone"
TB_RELL3NETWORKSECURITYZONE = "tb_rell3networksecurityzone"
V_RELL3NETWORKSECURITYZONE = "v_rell3networksecurityzone"
TB_SECURITYZONERULE = "tb_securityzonerule"
TB_RELVMNICSECURITYZONE = "tb_relvmnicsecurityzone"
V_RELVMNICSECURITYZONE = "v_relvmnicsecurityzone"
V_RELVMPRIMARYSTORAGE = "v_relvmprimarystorage"
V_RELIMAGEBACKUPSTORAGE = "v_relimagebackupstorage"

V_PRIMARYSTORAGE = "v_primarystorage"
V_PRIMARYSTORAGEPOOL = "v_primarystoragepool"
V_HOSTPOOL = "v_hostpool"
V_HOST = "v_host"
V_HOSTSTORAGE = "v_hoststorage"
V_BACKUPSTORAGE = "v_backupstorage"
V_IMAGE = "v_image"
V_IMAGECACHE = "v_imagecache"
V_L2NETWORK = "v_l2network"
V_L3NETWORK = "v_l3network"
V_IPPOOL = "v_ippool"
V_VIP = "v_vip"
V_EIP = "v_eip"
V_VIRTUALROUTEROFFERING = "v_virtualrouteroffering"
V_PORTFORWARDINGRULE = "v_portforwardingrule"
V_SERVERPRIMARYSTORAGE = "v_sprimarystorage"
V_SVM = "v_svm"
V_VM = "v_vm"
TB_VOLUME = "tb_volume"
V_VOLUME = "v_volume"
TB_VOLUMESNAPSHOT = "tb_volumesnapshot"
V_VOLUMESNAPSHOT = "v_volumesnapshot"
TB_VOLUMESNAPSHOTTREE = "tb_volumesnapshottree"
TB_VMNIC = "tb_vmnic"
V_VMNIC = "v_vmnic"
TB_VMCDROM = "tb_vmcdrom"
V_VMCDROM = "v_vmcdrom"
TB_CONSOLEPROXY = "tb_consoleproxy"

TB_RELVIRTUALROUTERL3NETWORK = "tb_relvirtualrouterl3network"
V_VIRTUALROUTERVM = "v_virtualroutervm"

TB_GLOBALCONFIG = "tb_globalconfig"
TB_RULE = "tb_rule"

TB_VMGROUP = "tb_vmgroup"
V_VMGROUP = "v_vmgroup"

#Class TB Region
#Teacher
TB_TEACHER = "tb_teacher"
TB_CLASS = "tb_class"
TB_STUDENT = "tb_student"
TB_RCS = "tb_rel_class_student"
V_STUDENT = "v_student"
TB_ROOM = "tb_room"
V_ROOM = "v_room"
TB_COURSE = "tb_course"
V_COURSE_BIND = "v_course_bind"
V_COURSE_RANDOM = "v_course_random"
TB_RTC = "tb_rel_teacher_course"
TB_TIMER = "tb_timer"
TB_COURSE_LOG = "tb_course_log"
V_COURSE_TEMPLATE = "v_course_template"

def get_sock_file():
	if (os.path.exists(UNIXSOCKET_DEBIAN)):
		return UNIXSOCKET_DEBIAN
	else:
		return UNIXSOCKET_REDCENT
